import type { Scene } from "./types";

export const delhiTapri: Scene = {
  id: "delhi-tapri",
  city: "Delhi",
  speaker: "RAJU",
  language: "Hindi",
  locale: "hi-IN",
  nativeTitle: "चाय की टपरी",
  deckLine: "Night tapri. Order cutting chai.",
  seedImage: "/scenes/delhi-street.jpg",
  font: "deva",
  identity: [
    "AAA photoreal open-world night, Grand Theft Auto cinematic, Unreal Engine 5, 35mm anamorphic, Delhi, India.",
    "Camera is third-person in the wet road, wide 24mm, the STREET is the subject, vanishing point down the block. Do not crop to a face. Do not make a portrait.",
    "Near: rain-slick asphalt, puddles, sodium reflections, a plastic stool, a wet scooter tire.",
    "Mid: a roadside tapri on the right, one chaiwala in a faded blue checked shirt at a steel counter, brass kettle on a blue flame, steam. He is mid-ground, small in frame.",
    "Far: shop shutters, hanging wires, a red bus, motorbikes, living city blocks, a row of street lamps.",
    "Light: sodium on wet asphalt and ochre plaster, fluorescent on stall steel, cooker flame, red taillights in the distance.",
  ].join(" "),
  beats: {
    idle: "Wide living street. The chaiwala works the stall in mid-ground, wiping the counter. Steam, rain, traffic far down the block. Continuous handheld sway.",
    welcome:
      "The chaiwala smiles, presses his palms together in namaste, and nods the guest in. Warmer lamp light on his face, steam rising.",
    confused:
      "The chaiwala leans forward, brow furrowed, cupping one ear, puzzled. Two customers wait behind the camera. He shrugs and asks the guest to say it again.",
    almost:
      "The chaiwala nods slowly, not fully sure, holding an empty glass, waiting for a clearer order. Warm but hesitant.",
    served:
      "The chaiwala smiles and pours steaming cutting chai from the brass kettle into a small glass in one practiced motion, then slides it across the steel counter. Golden steam, warmer lamp light.",
    extra:
      "The chaiwala crushes fresh ginger into the kettle, masala rising in the steam, then pours a darker stronger chai with a proud little smile.",
    paid: "The chaiwala counts a few rupee notes, nods satisfied, another glass of chai on the counter, the stall glowing.",
    impatient:
      "A longer queue of three people waits behind the camera. The chaiwala glances at a wall clock, rain heavier on the street, tired and waiting.",
    complete:
      "The chaiwala raises a glass in a small toast, wide smile, stall bathed in warm lamp light, kettle steaming, a quiet happy night.",
  },
  opening: {
    native: "बोलो, क्या लेना है?",
    roman: "Bolo, kya lena hai?",
  },
  heritage: {
    title: "Cutting chai",
    native: "कटिंग चाय",
    body: "A half-glass of strong chai poured from a height at a tapri. Cutting means you share the boil — cheap, fast, and how Delhi actually drinks tea on the street.",
  },
  impatient: {
    native: "लाइन लंबी हो रही है भाई, जल्दी बोलो।",
    roman: "Line lambi ho rahi hai bhai, jaldi bolo.",
  },
  claude: {
    npc: "You are a Delhi chaiwala at a night tapri. Kind, dry, busy. Speak Hindi.",
    replyShape: "one short Hindi sentence in Devanagari",
  },
  steps: [
    {
      id: "greet",
      goal: "Greet him",
      tryLine: "Namaste",
      tryNative: "नमस्ते",
      successOutcome: "welcome",
      rightAny: [
        "namaste",
        "namaskar",
        "namaskaar",
        "namasthe",
        "नमस्ते",
        "नमस्कार",
        "salaam",
        "salam",
        "adaab",
        "adab",
      ],
      almostAny: ["hello", "hi", "hey", "good evening", "good morning"],
      replies: {
        right: {
          native: "हाँ भाई, बोलो। क्या लेना है?",
          roman: "Haan bhai, bolo. Kya lena hai?",
          hint: "Ask for a cutting chai.",
        },
        almost: {
          native: "आ जाओ। हिंदी में नमस्ते बोलो तो मज़ा आए।",
          roman: "Aa jao. Hindi mein namaste bolo to mazaa aaye.",
          hint: "Try “Namaste” — that’s the door.",
        },
        wrong: {
          native: "हाँ? फिर से बोलो, आवाज़ नहीं आई।",
          roman: "Haan? Phir se bolo, awaaz nahi aayi.",
          hint: "A greeting first. “Namaste” is enough.",
        },
      },
    },
    {
      id: "order",
      goal: "Order chai",
      tryLine: "Ek cutting chai dena",
      tryNative: "एक कटिंग चाय देना",
      successOutcome: "served",
      rightAny: ["chai", "chay", "chaye", "tea", "चाय", "cutting"],
      rightAlso: [
        "dena",
        "do",
        "chahiye",
        "please",
        "ek",
        "ekk",
        "one",
        "cup",
        "glass",
        "gilaas",
        "देना",
        "दो",
        "चाहिए",
        "एक",
      ],
      almostAny: ["chai", "chay", "tea", "चाय", "cutting"],
      replies: {
        right: {
          native: "एक कटिंग। अदरक वाली चाहिए या सादी?",
          roman: "Ek cutting. Adrak wali chahiye ya saadi?",
          hint: "Tell him you want it adrak wali, kadak.",
        },
        almost: {
          native: "चाय? कटिंग? साफ़-साफ़ बोलो।",
          roman: "Chai? Cutting? Saaf-saaf bolo.",
          hint: "Say you want one — “Ek cutting chai dena.”",
        },
        wrong: {
          native: "भाई चाय लेनी है तो बोलो। मेनू नहीं है, केतली है।",
          roman: "Bhai chai leni hai to bolo. Menu nahi hai, kettle hai.",
          hint: "Order a tea. “Ek chai dena” works.",
        },
      },
    },
    {
      id: "specify",
      goal: "Make it yours",
      tryLine: "Adrak wali, kadak",
      tryNative: "अदरक वाली, कड़क",
      successOutcome: "extra",
      rightAny: [
        "adrak",
        "adrakwali",
        "ginger",
        "masala",
        "kadak",
        "elaichi",
        "elachi",
        "अदरक",
        "मसाला",
        "कड़क",
        "कडक",
        "इलायची",
      ],
      almostAny: ["garam", "strong", "extra", "sweet", "cheeni", "sugar", "गरम"],
      replies: {
        right: {
          native: "अदरक डाल देता हूँ। गरम-गरम।",
          roman: "Adrak daal deta hoon. Garam-garam.",
          hint: "Ask what it costs — “Kitne ka hai?”",
        },
        almost: {
          native: "गरम ही बनेगी। अदरक, मसाला, कड़क — कुछ तो बोलो।",
          roman: "Garam hi banegi. Adrak, masala, kadak — kuch to bolo.",
          hint: "Pick a style: adrak, masala, or kadak.",
        },
        wrong: {
          native: "क्या डालूँ? अदरक? मसाला? कुछ समझ नहीं आया।",
          roman: "Kya daalun? Adrak? Masala? Kuch samajh nahi aaya.",
          hint: "Say “adrak wali” or “kadak.”",
        },
      },
    },
    {
      id: "price",
      goal: "Ask the price",
      tryLine: "Kitne ka hai?",
      tryNative: "कितने का है?",
      successOutcome: "paid",
      rightAny: [
        "kitne",
        "kitna",
        "daam",
        "price",
        "cost",
        "how much",
        "rupaye",
        "rupee",
        "कितने",
        "कितना",
        "दाम",
        "कीमत",
      ],
      almostAny: ["bill", "hisab", "hisaab", "paisa", "paise", "pay", "हिसाब"],
      replies: {
        right: {
          native: "बीस रुपये। गिलास गरम है, संभाल के।",
          roman: "Bees rupaye. Gilaas garam hai, sambhal ke.",
          hint: "Close it with thanks — “Shukriya.”",
        },
        almost: {
          native: "पैसे? हाँ, दाम पूछो — कितने का है?",
          roman: "Paise? Haan, daam poocho — kitne ka hai?",
          hint: "Ask the price in Hindi: “Kitne ka hai?”",
        },
        wrong: {
          native: "अभी हिसाब? पहले दाम पूछो भाई।",
          roman: "Abhi hisaab? Pehle daam poocho bhai.",
          hint: "Ask “Kitne ka hai?”",
        },
      },
    },
    {
      id: "thanks",
      goal: "Thank him",
      tryLine: "Shukriya",
      tryNative: "शुक्रिया",
      successOutcome: "complete",
      rightAny: [
        "shukriya",
        "shukria",
        "sukriya",
        "dhanyavad",
        "dhanyavaad",
        "thanks",
        "thank you",
        "thankyou",
        "शुक्रिया",
        "धन्यवाद",
      ],
      almostAny: ["bye", "accha", "theek", "ok", "okay", "alvida", "अच्छा"],
      replies: {
        right: {
          native: "फिर आना। चाय गरम रहेगी।",
          roman: "Phir aana. Chai garam rahegi.",
          hint: "That’s the loop. The stall remembers you.",
        },
        almost: {
          native: "हाँ ठीक है। शुक्रिया बोल दो, अच्छा लगता है।",
          roman: "Haan theek hai. Shukriya bol do, accha lagta hai.",
          hint: "One word: “Shukriya.”",
        },
        wrong: {
          native: "जाना है तो शुक्रिया कह के जाना।",
          roman: "Jaana hai to shukriya keh ke jaana.",
          hint: "Thank him. “Shukriya” or “Dhanyavaad.”",
        },
      },
    },
  ],
};
