import type { Encounter } from "../district";
import { line, step } from "./make";

export const delhiEncounters: Encounter[] = [
  {
    key: "hotel_food",
    speaker: "RAJU",
    x: 7.2,
    z: 3.1,
    view: "Mid: a roadside tapri on the right, chaiwala in a blue checked shirt, brass kettle, steam in sun.",
    opening: { native: "बोलो, क्या लेना है?", roman: "Bolo, kya lena hai?" },
    heritage: {
      title: "Cutting chai",
      native: "कटिंग चाय",
      body: "A half-glass of strong chai poured from a height. Cutting means you share the boil.",
    },
    impatient: { native: "लाइन लंबी हो रही है भाई, जल्दी बोलो।", roman: "Line lambi ho rahi hai bhai, jaldi bolo." },
    claude: { npc: "You are a Delhi chaiwala. Kind, dry, busy. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "greet",
        goal: "Greet him",
        tryLine: "Namaste",
        tryNative: "नमस्ते",
        successOutcome: "welcome",
        rightAny: ["namaste", "namaskar", "नमस्ते"],
        almostAny: ["hello", "hi"],
        replies: {
          right: line("हाँ भाई, बोलो। क्या लेना है?", "Haan bhai, bolo.", "Ask for a cutting chai."),
          almost: line("आ जाओ। हिंदी में नमस्ते बोलो।", "Aa jao. Hindi mein namaste bolo.", "Try “Namaste”."),
          wrong: line("हाँ? फिर से बोलो।", "Haan? Phir se bolo.", "A greeting first."),
        },
      }),
      step({
        id: "order",
        goal: "Order chai",
        tryLine: "Ek cutting chai dena",
        tryNative: "एक कटिंग चाय देना",
        successOutcome: "served",
        rightAny: ["chai", "चाय", "cutting"],
        rightAlso: ["dena", "do", "ek", "देना", "एक"],
        almostAny: ["tea"],
        replies: {
          right: line("एक कटिंग। अदरक वाली?", "Ek cutting. Adrak wali?", "Ask the price."),
          almost: line("चाय? साफ़-साफ़ बोलो।", "Chai? Saaf-saaf bolo.", "Say “Ek cutting chai dena.”"),
          wrong: line("चाय लेनी है तो बोलो।", "Chai leni hai to bolo.", "Order a tea."),
        },
      }),
      step({
        id: "price",
        goal: "Ask the price",
        tryLine: "Kitne ka hai?",
        tryNative: "कितने का है?",
        successOutcome: "complete",
        rightAny: ["kitne", "kitna", "कितने", "कितना"],
        almostAny: ["price", "bill"],
        replies: {
          right: line("बीस रुपये। संभाल के।", "Bees rupaye.", "That’s the loop."),
          almost: line("दाम पूछो — कितने का है?", "Daam poocho — kitne ka hai?", "Ask “Kitne ka hai?”"),
          wrong: line("पहले दाम पूछो भाई।", "Pehle daam poocho bhai.", "Ask the price."),
        },
      }),
    ],
  },
  {
    key: "market_shopping",
    speaker: "KAMALA",
    x: 2.8,
    z: 5.2,
    view: "Mid: a vegetable cart under a tarp, a woman shopkeeper, tomatoes and coriander in daylight.",
    opening: { native: "क्या लेना है बेटा?", roman: "Kya lena hai beta?" },
    heritage: {
      title: "Sabzi mandi",
      native: "सब्ज़ी मंडी",
      body: "You bargain. Asking the price is the first respect.",
    },
    impatient: { native: "और लोग भी हैं, जल्दी बताओ।", roman: "Aur log bhi hain, jaldi batao." },
    claude: { npc: "You are a Delhi sabziwali. Warm, sharp. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "ask",
        goal: "Ask the price",
        tryLine: "Tamatar kitne kilo?",
        tryNative: "टमाटर कितने किलो?",
        successOutcome: "welcome",
        rightAny: ["tamatar", "टमाटर", "kitne", "कितने"],
        almostAny: ["tomato", "price"],
        replies: {
          right: line("चालीस रुपये किलो। कितना दूँ?", "Chalees rupaye kilo.", "Say you want half a kilo."),
          almost: line("टमाटर? दाम पूछो हिंदी में।", "Tamatar? Daam poocho Hindi mein.", "“Tamatar kitne kilo?”"),
          wrong: line("क्या चाहिए? टमाटर, प्याज़?", "Kya chahiye?", "Ask for tomatoes."),
        },
      }),
      step({
        id: "bargain",
        goal: "Bargain a little",
        tryLine: "Thoda kam karo",
        tryNative: "थोड़ा कम करो",
        successOutcome: "extra",
        rightAny: ["kam", "कम", "sasta", "सस्ता"],
        almostAny: ["cheap", "less"],
        replies: {
          right: line("अच्छा, पैंतीस। आधा किलो?", "Accha, paintis.", "Take half a kilo."),
          almost: line("कम? साफ़ बोलो — थोड़ा कम करो।", "Kam? Thoda kam karo.", "Say “Thoda kam karo.”"),
          wrong: line("भाव ये ही है। कुछ और?", "Bhaav yehi hai.", "Bargain: “Thoda kam karo.”"),
        },
      }),
      step({
        id: "take",
        goal: "Take it",
        tryLine: "Aadha kilo dena",
        tryNative: "आधा किलो देना",
        successOutcome: "complete",
        rightAny: ["kilo", "किलो", "dena", "देना", "aadha", "आधा"],
        almostAny: ["half", "give"],
        replies: {
          right: line("लो, तौल दिया।", "Lo, taul diya.", "That’s the mandi."),
          almost: line("कितना? आधा किलो बोलो।", "Kitna? Aadha kilo bolo.", "“Aadha kilo dena.”"),
          wrong: line("लेना है तो बताओ।", "Lena hai to batao.", "Say how much."),
        },
      }),
    ],
  },
  {
    key: "travel_auto",
    speaker: "IMRAN",
    x: 5.1,
    z: 1.4,
    view: "Mid: a yellow-green CNG auto at the curb, driver on the seat, meter, dry road.",
    opening: { native: "कहाँ जाना है?", roman: "Kahan jaana hai?" },
    heritage: {
      title: "Auto meter",
      native: "ऑटो मीटर",
      body: "Ask if he will go by meter. That sentence is the whole negotiation.",
    },
    impatient: { native: "भाई फैसला करो, और सवारी है।", roman: "Bhai faisla karo." },
    claude: { npc: "You are a Delhi auto driver. Fast, fair if you are clear. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "where",
        goal: "Say where",
        tryLine: "Connaught Place chalna hai",
        tryNative: "कॉनॉट प्लेस चलना है",
        successOutcome: "welcome",
        rightAny: ["connaught", "cp", "कॉनॉट", "chalna", "चलना", "jaana", "जाना"],
        almostAny: ["please", "go"],
        replies: {
          right: line("मीटर से चलूँ?", "Meter se chalun?", "Ask for the meter."),
          almost: line("कहाँ? साफ़ बोलो।", "Kahan? Saaf bolo.", "Name the place."),
          wrong: line("कहाँ जाना है भाई?", "Kahan jaana hai bhai?", "Say the destination."),
        },
      }),
      step({
        id: "meter",
        goal: "Ask for meter",
        tryLine: "Meter se chaloge?",
        tryNative: "मीटर से चलोगे?",
        successOutcome: "paid",
        rightAny: ["meter", "मीटर"],
        almostAny: ["fare", "kitne"],
        replies: {
          right: line("ठीक है, बैठो।", "Theek hai, baitho.", "Thank him."),
          almost: line("भाव? मीटर बोलो।", "Bhaav? Meter bolo.", "“Meter se chaloge?”"),
          wrong: line("फिक्स्ड नहीं, मीटर से।", "Fixed nahi, meter se.", "Ask for the meter."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Shukriya",
        tryNative: "शुक्रिया",
        successOutcome: "complete",
        rightAny: ["shukriya", "शुक्रिया", "dhanyavad", "धन्यवाद"],
        almostAny: ["thanks", "bye"],
        replies: {
          right: line("आराम से बैठो।", "Aaram se baitho.", "You’re in."),
          almost: line("शुक्रिया बोल दो।", "Shukriya bol do.", "“Shukriya.”"),
          wrong: line("जाने से पहले एक शब्द।", "Jaane se pehle ek shabd.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "travel_bus",
    speaker: "SURESH",
    x: 8.4,
    z: 7.1,
    view: "Mid: an open DTC bus doorway, conductor with a ticket pouch. Far: red bus body, commuters.",
    opening: { native: "कहाँ जाना है, टिकट ले लो।", roman: "Kahan jaana hai, ticket le lo." },
    heritage: {
      title: "Bus ticket",
      native: "बस टिकट",
      body: "You name the stop. He tears the ticket. That is the whole contract.",
    },
    impatient: { native: "आगे बढ़ो, और लोग हैं।", roman: "Aage badho." },
    claude: { npc: "You are a Delhi bus conductor. Loud, efficient. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "stop",
        goal: "Name the stop",
        tryLine: "AIIMS ke liye ticket",
        tryNative: "एम्स के लिए टिकट",
        successOutcome: "welcome",
        rightAny: ["ticket", "टिकट", "aiims", "एम्स", "stop"],
        almostAny: ["please", "bus"],
        replies: {
          right: line("दस रुपये। पैसे दो।", "Das rupaye.", "Pay him."),
          almost: line("कौन सा स्टॉप? टिकट बोलो।", "Kaun sa stop?", "Name the stop and ticket."),
          wrong: line("टिकट लेना है तो स्टॉप बोलो।", "Ticket lena hai to stop bolo.", "Ask for a ticket."),
        },
      }),
      step({
        id: "pay",
        goal: "Pay",
        tryLine: "Yeh lo",
        tryNative: "यह लो",
        successOutcome: "paid",
        rightAny: ["lo", "लो", "rupaye", "रुपये", "ten", "das", "दस"],
        almostAny: ["money", "pay"],
        replies: {
          right: line("टिकट, संभाल के।", "Ticket, sambhal ke.", "Thank him."),
          almost: line("पैसे दो — यह लो।", "Paise do — yeh lo.", "Hand him the money."),
          wrong: line("पैसे?", "Paise?", "Pay for the ticket."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Shukriya",
        tryNative: "शुक्रिया",
        successOutcome: "complete",
        rightAny: ["shukriya", "शुक्रिया", "dhanyavad", "धन्यवाद"],
        almostAny: ["thanks"],
        replies: {
          right: line("आगे खड़े रहना।", "Aage khade rahna.", "Hold on."),
          almost: line("शुक्रिया कह दो।", "Shukriya keh do.", "“Shukriya.”"),
          wrong: line("एक शब्द और।", "Ek shabd aur.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "random_stranger",
    speaker: "NEHA",
    x: 4.2,
    z: 4.4,
    view: "Mid: a young woman under a shop awning, phone in hand, dry afternoon street.",
    opening: { native: "हाँ, बोलिए?", roman: "Haan, boliye?" },
    heritage: {
      title: "Maaf kijiye",
      native: "माफ़ कीजिए",
      body: "On a Delhi street you open with sorry, then the ask. Not hi.",
    },
    impatient: { native: "जी, जल्दी बोलिए।", roman: "Ji, jaldi boliye." },
    claude: { npc: "You are a Delhi stranger, polite but busy. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "excuse",
        goal: "Excuse yourself",
        tryLine: "Maaf kijiye",
        tryNative: "माफ़ कीजिए",
        successOutcome: "welcome",
        rightAny: ["maaf", "माफ़", "sorry", "sunie", "सुनिए"],
        almostAny: ["hello", "excuse"],
        replies: {
          right: line("जी, बताइए।", "Ji, bataiye.", "Ask for India Gate."),
          almost: line("हिंदी में माफ़ कीजिए।", "Hindi mein maaf kijiye.", "“Maaf kijiye.”"),
          wrong: line("जी?", "Ji?", "Start with “Maaf kijiye.”"),
        },
      }),
      step({
        id: "ask",
        goal: "Ask the way",
        tryLine: "India Gate kidhar hai?",
        tryNative: "इंडिया गेट किधर है?",
        successOutcome: "served",
        rightAny: ["kidhar", "किधर", "kahan", "कहाँ", "gate", "गेट"],
        almostAny: ["where", "way"],
        replies: {
          right: line("सीधे जाइए, फिर बाएँ।", "Seedhe jaiye, phir baayen.", "Thank her."),
          almost: line("कहाँ जाना है? किधर है, बोलो।", "Kahan jaana hai?", "“Kidhar hai?”"),
          wrong: line("क्या पूछना है?", "Kya poochna hai?", "Ask where it is."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank her",
        tryLine: "Shukriya",
        tryNative: "शुक्रिया",
        successOutcome: "complete",
        rightAny: ["shukriya", "शुक्रिया", "dhanyavad", "धन्यवाद"],
        almostAny: ["thanks"],
        replies: {
          right: line("कोई बात नहीं।", "Koi baat nahi.", "That’s the street."),
          almost: line("शुक्रिया कह दीजिए।", "Shukriya keh dijiye.", "“Shukriya.”"),
          wrong: line("एक शब्द और।", "Ek shabd aur.", "Thank her."),
        },
      }),
    ],
  },
  {
    key: "police_traffic",
    speaker: "YADAV",
    x: 6.3,
    z: 8.2,
    view: "Mid: a traffic cop in a white-and-blue uniform, a checkpoint cone, daylight.",
    opening: { native: "रुकिए। लाइसेंस दिखाइए।", roman: "Rukiye. License dikhaiye." },
    heritage: {
      title: "Checkpoint",
      native: "चेक पोस्ट",
      body: "You stop. You show. You stay polite. That is the whole scene.",
    },
    impatient: { native: "जल्दी दिखाइए, लाइन है।", roman: "Jaldi dikhaiye." },
    claude: { npc: "You are a Delhi traffic officer. Firm, not cruel. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "stop",
        goal: "Acknowledge",
        tryLine: "Ji",
        tryNative: "जी",
        successOutcome: "welcome",
        rightAny: ["ji", "जी", "haan", "हाँ"],
        almostAny: ["yes", "ok"],
        replies: {
          right: line("लाइसेंस।", "License.", "Say you have it."),
          almost: line("जी बोलिए।", "Ji boliye.", "“Ji.”"),
          wrong: line("सुना? रुकिए।", "Suna? Rukiye.", "Answer him."),
        },
      }),
      step({
        id: "license",
        goal: "Show license",
        tryLine: "Yeh lijiye",
        tryNative: "यह लीजिए",
        successOutcome: "paid",
        rightAny: ["lijiye", "लीजिए", "license", "लाइसेंस", "yeh", "यह"],
        almostAny: ["here", "card"],
        replies: {
          right: line("ठीक है, जा सकते हैं।", "Theek hai, ja sakte hain.", "Thank him."),
          almost: line("दिखाइए — यह लीजिए।", "Dikhaiye — yeh lijiye.", "Hand it over."),
          wrong: line("लाइसेंस कहाँ है?", "License kahan hai?", "Show the license."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Shukriya",
        tryNative: "शुक्रिया",
        successOutcome: "complete",
        rightAny: ["shukriya", "शुक्रिया", "dhanyavad", "धन्यवाद"],
        almostAny: ["thanks"],
        replies: {
          right: line("सावधानी से।", "Savdhani se.", "Go."),
          almost: line("शुक्रिया कहिए।", "Shukriya kahiye.", "“Shukriya.”"),
          wrong: line("जाइए।", "Jaiye.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "on_a_date",
    speaker: "MIRA",
    x: 1.8,
    z: 6.4,
    view: "Mid: a small café table in late-day sun, a woman with a glass of chai.",
    opening: { native: "देर हो गई थी क्या?", roman: "Der ho gayi thi kya?" },
    heritage: {
      title: "Café chai",
      native: "कैफ़े चाय",
      body: "You sit. You ask how they are. Hindi first dates start small.",
    },
    impatient: { native: "अरे, कुछ तो बोलो।", roman: "Are, kuch to bolo." },
    claude: { npc: "You are on a first date in Delhi. Warm, teasing. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "hi",
        goal: "Greet her",
        tryLine: "Namaste, kaisi ho?",
        tryNative: "नमस्ते, कैसी हो?",
        successOutcome: "welcome",
        rightAny: ["namaste", "नमस्ते", "kaisi", "कैसी", "kaise", "कैसे"],
        almostAny: ["hello", "hi"],
        replies: {
          right: line("मैं ठीक हूँ। तुम क्या लोगे?", "Main theek hoon.", "Order chai."),
          almost: line("नमस्ते तो बोलो।", "Namaste to bolo.", "Greet her in Hindi."),
          wrong: line("हाँ?", "Haan?", "Say hello."),
        },
      }),
      step({
        id: "order",
        goal: "Order for the table",
        tryLine: "Do cutting chai",
        tryNative: "दो कटिंग चाय",
        successOutcome: "served",
        rightAny: ["chai", "चाय", "do", "दो"],
        almostAny: ["tea", "coffee"],
        replies: {
          right: line("अच्छा। बात करते हैं।", "Accha. Baat karte hain.", "Thank her."),
          almost: line("चाय? दो बोलो।", "Chai? Do bolo.", "“Do cutting chai.”"),
          wrong: line("कुछ मँगवाएँ?", "Kuch mangwayen?", "Order two chai."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank her",
        tryLine: "Shukriya",
        tryNative: "शुक्रिया",
        successOutcome: "complete",
        rightAny: ["shukriya", "शुक्रिया", "accha", "अच्छा"],
        almostAny: ["thanks"],
        replies: {
          right: line("फेर मिलते हैं।", "Phir milte hain.", "That’s the table."),
          almost: line("शुक्रिया कह दो।", "Shukriya keh do.", "“Shukriya.”"),
          wrong: line("एक अच्छी बात और।", "Ek acchi baat aur.", "Thank her."),
        },
      }),
    ],
  },
  {
    key: "school_teacher",
    speaker: "SHARMA",
    x: 1.2,
    z: 2.2,
    view: "Mid: a school gate, a teacher with a register in morning light.",
    opening: { native: "हाँ, बोलो। होमवर्क आया?", roman: "Haan, bolo. Homework aaya?" },
    heritage: {
      title: "Sir / Ma'am",
      native: "सर",
      body: "You address the teacher first. Then the ask.",
    },
    impatient: { native: "जल्दी, घंटी बज गई।", roman: "Jaldi, ghanti baj gayi." },
    claude: { npc: "You are a Delhi school teacher. Crisp, kind. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "sir",
        goal: "Address the teacher",
        tryLine: "Namaste sir",
        tryNative: "नमस्ते सर",
        successOutcome: "welcome",
        rightAny: ["sir", "सर", "namaste", "नमस्ते", "maam"],
        almostAny: ["hello", "teacher"],
        replies: {
          right: line("बोलो, क्या बात है?", "Bolo, kya baat hai?", "Ask about homework."),
          almost: line("सर कहो।", "Sir kaho.", "“Namaste sir.”"),
          wrong: line("हाँ?", "Haan?", "Greet the teacher."),
        },
      }),
      step({
        id: "ask",
        goal: "Ask about homework",
        tryLine: "Homework kab dena hai?",
        tryNative: "होमवर्क कब देना है?",
        successOutcome: "served",
        rightAny: ["homework", "होमवर्क", "kab", "कब"],
        almostAny: ["when", "assignment"],
        replies: {
          right: line("कल तक। समझ आ गया?", "Kal tak.", "Thank him."),
          almost: line("कब? पूछो — कब देना है?", "Kab? Poocho.", "Ask when it is due."),
          wrong: line("क्या पूछना है?", "Kya poochna hai?", "Ask about homework."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Dhanyavaad",
        tryNative: "धन्यवाद",
        successOutcome: "complete",
        rightAny: ["dhanyavad", "धन्यवाद", "shukriya", "शुक्रिया"],
        almostAny: ["thanks"],
        replies: {
          right: line("जाओ, क्लास लग गई।", "Jao, class lag gayi.", "Go."),
          almost: line("धन्यवाद बोलो।", "Dhanyavaad bolo.", "“Dhanyavaad.”"),
          wrong: line("एक शब्द।", "Ek shabd.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "friends_marriage",
    speaker: "AUNTY",
    x: 9.1,
    z: 5.0,
    view: "Mid: a wedding shamiana edge, marigold, an aunt in a bright sari. Far: fairy lights, dhol leftover.",
    opening: { native: "आ जाओ! खाया कि नहीं?", roman: "Aa jao! Khaya ki nahi?" },
    heritage: {
      title: "Shaadi",
      native: "शादी",
      body: "You bless the couple, then you eat. That is the duty.",
    },
    impatient: { native: "मिलो भी, खड़े मत रहो।", roman: "Milo bhi." },
    claude: { npc: "You are a relative at a Delhi wedding. Warm, nosy. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "bless",
        goal: "Bless the couple",
        tryLine: "Mubarak ho",
        tryNative: "मुबारक हो",
        successOutcome: "welcome",
        rightAny: ["mubarak", "मुबारक", "badhai", "बधाई"],
        almostAny: ["congrats", "hello"],
        replies: {
          right: line("बैठो, खाओ।", "Baitho, khao.", "Say you already ate."),
          almost: line("मुबारक तो बोलो।", "Mubarak to bolo.", "“Mubarak ho.”"),
          wrong: line("आए हो तो बोलो भी।", "Aaye ho to bolo bhi.", "Bless them."),
        },
      }),
      step({
        id: "food",
        goal: "Answer about food",
        tryLine: "Haan, kha liya",
        tryNative: "हाँ, खा लिया",
        successOutcome: "served",
        rightAny: ["kha", "खा", "liya", "लिया", "haan", "हाँ"],
        almostAny: ["ate", "food"],
        replies: {
          right: line("अच्छा। मिठाई और लो।", "Accha. Mithai aur lo.", "Thank her."),
          almost: line("खाया? हाँ, खा लिया।", "Khaya? Haan, kha liya.", "Say you ate."),
          wrong: line("भूख लगी है?", "Bhookh lagi hai?", "Tell her you ate."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank her",
        tryLine: "Shukriya aunty",
        tryNative: "शुक्रिया आंटी",
        successOutcome: "complete",
        rightAny: ["shukriya", "शुक्रिया", "aunty", "आंटी"],
        almostAny: ["thanks"],
        replies: {
          right: line("जल्दी आना फिर।", "Jaldi aana phir.", "That’s the tent."),
          almost: line("आंटी कह के शुक्रिया।", "Aunty keh ke shukriya.", "“Shukriya aunty.”"),
          wrong: line("एक प्यार का शब्द।", "Ek pyaar ka shabd.", "Thank her."),
        },
      }),
    ],
  },
  {
    key: "doctor_visit",
    speaker: "DR MEHTA",
    x: 2.4,
    z: 9.0,
    view: "Mid: a clinic doorway, a doctor in a white coat, a stethoscope. Far: a green cross, a queue.",
    opening: { native: "हाँ, क्या तकलीफ़ है?", roman: "Haan, kya takleef hai?" },
    heritage: {
      title: "Takleef",
      native: "तकलीफ़",
      body: "You name the symptom, not the story. The doctor asks the rest.",
    },
    impatient: { native: "अगला मरीज़ इंतज़ार में है।", roman: "Agla mareez intezaar mein hai." },
    claude: { npc: "You are a Delhi clinic doctor. Calm, brief. Speak Hindi.", replyShape: "one short Hindi sentence" },
    steps: [
      step({
        id: "symptom",
        goal: "Name the symptom",
        tryLine: "Sir dard hai",
        tryNative: "सिर दर्द है",
        successOutcome: "welcome",
        rightAny: ["dard", "दर्द", "sir", "सिर", "bukhar", "बुखार"],
        almostAny: ["pain", "head", "sick"],
        replies: {
          right: line("कब से? दवा देता हूँ।", "Kab se? Dava deta hoon.", "Ask what to take."),
          almost: line("दर्द? सिर दर्द है, बोलो।", "Dard? Sir dard hai, bolo.", "Name the pain."),
          wrong: line("क्या हुआ?", "Kya hua?", "Say what hurts."),
        },
      }),
      step({
        id: "ask",
        goal: "Ask for medicine",
        tryLine: "Kaunsi dawai lun?",
        tryNative: "कौन सी दवाई लूँ?",
        successOutcome: "served",
        rightAny: ["dawai", "दवाई", "dava", "दवा", "kaunsi", "कौन"],
        almostAny: ["medicine", "tablet"],
        replies: {
          right: line("यह गोली, खाने के बाद।", "Yeh goli, khane ke baad.", "Thank him."),
          almost: line("दवाई पूछो।", "Dawai poocho.", "“Kaunsi dawai lun?”"),
          wrong: line("कुछ और?", "Kuch aur?", "Ask for the medicine."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Shukriya doctor",
        tryNative: "शुक्रिया डॉक्टर",
        successOutcome: "complete",
        rightAny: ["shukriya", "शुक्रिया", "doctor", "डॉक्टर"],
        almostAny: ["thanks"],
        replies: {
          right: line("आराम से। पानी पीना।", "Aaram se. Pani peena.", "That’s the clinic."),
          almost: line("डॉक्टर कह के शुक्रिया।", "Doctor keh ke shukriya.", "“Shukriya doctor.”"),
          wrong: line("एक शब्द।", "Ek shabd.", "Thank him."),
        },
      }),
    ],
  },
];
