import type { Encounter } from "../district";
import { line, step } from "./make";

export const tokyoEncounters: Encounter[] = [
  {
    key: "hotel_food",
    speaker: "KENJI",
    x: 7.2,
    z: 3.1,
    view: "Mid: a ramen yatai, cook in a white shirt, steam, noren, lanterns just on.",
    opening: { native: "いらっしゃい。何にする？", roman: "Irasshai. Nani ni suru?" },
    heritage: {
      title: "Irasshaimase",
      native: "いらっしゃいませ",
      body: "You sit. You order. The cook already knows you are hungry.",
    },
    impatient: { native: "他のお客さんが待ってるよ。", roman: "Hoka no okyaku ga matteru yo." },
    claude: { npc: "You are a Tokyo ramen cook. Warm, brief. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "greet",
        goal: "Greet him",
        tryLine: "Konbanwa",
        tryNative: "こんばんは",
        successOutcome: "welcome",
        rightAny: ["konbanwa", "こんばんは", "konnichiwa", "こんにちは"],
        almostAny: ["hello", "hi"],
        replies: {
          right: line("どうぞ。何にする？", "Douzo. Nani ni suru?", "Order ramen."),
          almost: line("日本語でこんばんは。", "Nihongo de konbanwa.", "“Konbanwa.”"),
          wrong: line("ん？もう一回。", "N? Mou ikkai.", "Greet him."),
        },
      }),
      step({
        id: "order",
        goal: "Order ramen",
        tryLine: "Ramen kudasai",
        tryNative: "ラーメンください",
        successOutcome: "served",
        rightAny: ["ramen", "ラーメン", "kudasai", "ください"],
        almostAny: ["please", "noodles"],
        replies: {
          right: line("はい、少々お待ちを。", "Hai, shoushou omachi wo.", "Ask the price."),
          almost: line("ラーメン？はっきり言って。", "Ramen? Hakkiri itte.", "“Ramen kudasai.”"),
          wrong: line("何にする？", "Nani ni suru?", "Order ramen."),
        },
      }),
      step({
        id: "price",
        goal: "Ask the price",
        tryLine: "Ikura desu ka?",
        tryNative: "いくらですか？",
        successOutcome: "complete",
        rightAny: ["ikura", "いくら"],
        almostAny: ["price", "yen"],
        replies: {
          right: line("八百円。どうぞ。", "Happyaku en.", "That’s the stall."),
          almost: line("値段は？いくらですか。", "Nedan wa? Ikura desu ka.", "Ask “Ikura desu ka?”"),
          wrong: line("先に値段を聞いて。", "Saki ni nedan wo kiite.", "Ask the price."),
        },
      }),
    ],
  },
  {
    key: "market_shopping",
    speaker: "YUMI",
    x: 2.8,
    z: 5.2,
    view: "Mid: a narrow grocer, crates of fruit, a woman shopkeeper in morning sun.",
    opening: { native: "いらっしゃい。何をお探し？", roman: "Irasshai. Nani wo osagashi?" },
    heritage: {
      title: "Yaoya",
      native: "八百屋",
      body: "You name the fruit and ask how much. That is the whole stall.",
    },
    impatient: { native: "他のお客さんもいるから。", roman: "Hoka no okyaku mo iru kara." },
    claude: { npc: "You are a Tokyo grocer. Polite, quick. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "ask",
        goal: "Ask the price",
        tryLine: "Ringo wa ikura?",
        tryNative: "りんごはいくら？",
        successOutcome: "welcome",
        rightAny: ["ringo", "りんご", "ikura", "いくら"],
        almostAny: ["apple", "price"],
        replies: {
          right: line("一つ百円。いくつ？", "Hitotsu hyaku en.", "Say two."),
          almost: line("りんご？いくら、聞いて。", "Ringo? Ikura, kiite.", "“Ringo wa ikura?”"),
          wrong: line("何がいい？", "Nani ga ii?", "Ask for apples."),
        },
      }),
      step({
        id: "qty",
        goal: "Say how many",
        tryLine: "Futatsu kudasai",
        tryNative: "二つください",
        successOutcome: "served",
        rightAny: ["futatsu", "二つ", "kudasai", "ください", "ni", "二"],
        almostAny: ["two", "please"],
        replies: {
          right: line("はい、どうぞ。", "Hai, douzo.", "Thank her."),
          almost: line("いくつ？二つください。", "Ikutsu? Futatsu kudasai.", "Say two."),
          wrong: line("いくつ要る？", "Ikutsu iru?", "Say how many."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank her",
        tryLine: "Arigatou gozaimasu",
        tryNative: "ありがとうございます",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう"],
        almostAny: ["thanks"],
        replies: {
          right: line("また来てね。", "Mata kite ne.", "That’s the shop."),
          almost: line("ありがとう、言って。", "Arigatou, itte.", "“Arigatou.”"),
          wrong: line("もう一言。", "Mou hitokoto.", "Thank her."),
        },
      }),
    ],
  },
  {
    key: "travel_auto",
    speaker: "TAKASHI",
    x: 5.1,
    z: 1.4,
    view: "Mid: a black taxi at the curb, driver window down, dry afternoon avenue.",
    opening: { native: "どちらまで？", roman: "Dochira made?" },
    heritage: {
      title: "Takushii",
      native: "タクシー",
      body: "You name the station. He already has the meter on.",
    },
    impatient: { native: "決めてください。", roman: "Kimete kudasai." },
    claude: { npc: "You are a Tokyo taxi driver. Brief, correct. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "where",
        goal: "Say where",
        tryLine: "Shibuya eki made",
        tryNative: "渋谷駅まで",
        successOutcome: "welcome",
        rightAny: ["shibuya", "渋谷", "eki", "駅", "made", "まで"],
        almostAny: ["please", "go"],
        replies: {
          right: line("メーターでいい？", "Meetaa de ii?", "Say yes to the meter."),
          almost: line("どこ？駅、言って。", "Doko? Eki, itte.", "Name the station."),
          wrong: line("どちらまで？", "Dochira made?", "Say the destination."),
        },
      }),
      step({
        id: "meter",
        goal: "Confirm meter",
        tryLine: "Onegaishimasu",
        tryNative: "お願いします",
        successOutcome: "paid",
        rightAny: ["onegaishimasu", "お願いします", "hai", "はい"],
        almostAny: ["yes", "ok"],
        replies: {
          right: line("どうぞ。", "Douzo.", "Thank him."),
          almost: line("お願いします、言って。", "Onegaishimasu, itte.", "Confirm."),
          wrong: line("乗るか？", "Noru ka?", "Confirm the ride."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Arigatou",
        tryNative: "ありがとう",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう"],
        almostAny: ["thanks"],
        replies: {
          right: line("シートベルトを。", "Shiitoberuto wo.", "You’re in."),
          almost: line("ありがとう。", "Arigatou.", "Thank him."),
          wrong: line("一言。", "Hitokoto.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "travel_bus",
    speaker: "SATO",
    x: 8.4,
    z: 7.1,
    view: "Mid: a Toei bus doorway, conductor with a fare box. Far: the green bus, commuters.",
    opening: { native: "どこまで？切符をどうぞ。", roman: "Doko made? Kippu wo douzo." },
    heritage: {
      title: "Kippu",
      native: "切符",
      body: "You name the stop. He punches the ticket.",
    },
    impatient: { native: "次の人が待ってます。", roman: "Tsugi no hito ga mattemasu." },
    claude: { npc: "You are a Tokyo bus conductor. Loud, efficient. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "stop",
        goal: "Name the stop",
        tryLine: "Shinjuku made kippu",
        tryNative: "新宿まで切符",
        successOutcome: "welcome",
        rightAny: ["kippu", "切符", "shinjuku", "新宿", "made", "まで"],
        almostAny: ["ticket", "please"],
        replies: {
          right: line("二百円。", "Nihyaku en.", "Pay him."),
          almost: line("停留所は？切符、言って。", "Teiryuujo wa?", "Name stop and ticket."),
          wrong: line("切符？どこまで？", "Kippu? Doko made?", "Ask for a ticket."),
        },
      }),
      step({
        id: "pay",
        goal: "Pay",
        tryLine: "Hai, douzo",
        tryNative: "はい、どうぞ",
        successOutcome: "paid",
        rightAny: ["hai", "はい", "douzo", "どうぞ", "en", "円"],
        almostAny: ["here", "pay"],
        replies: {
          right: line("切符、どうぞ。", "Kippu, douzo.", "Thank him."),
          almost: line("お金を — どうぞ。", "Okane wo — douzo.", "Hand him the money."),
          wrong: line("お金は？", "Okane wa?", "Pay."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Arigatou",
        tryNative: "ありがとう",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう"],
        almostAny: ["thanks"],
        replies: {
          right: line("奥へどうぞ。", "Oku e douzo.", "Hold on."),
          almost: line("ありがとう。", "Arigatou.", "Thank him."),
          wrong: line("一言。", "Hitokoto.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "random_stranger",
    speaker: "AKI",
    x: 4.2,
    z: 4.4,
    view: "Mid: a man by a konbini doorway, dry afternoon pavement.",
    opening: { native: "はい？", roman: "Hai?" },
    heritage: {
      title: "Sumimasen",
      native: "すみません",
      body: "On a Tokyo street you open with sorry, then the ask.",
    },
    impatient: { native: "急いでるんだけど。", roman: "Isoiderun dakedo." },
    claude: { npc: "You are a Tokyo stranger, polite but busy. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "excuse",
        goal: "Excuse yourself",
        tryLine: "Sumimasen",
        tryNative: "すみません",
        successOutcome: "welcome",
        rightAny: ["sumimasen", "すみません"],
        almostAny: ["excuse", "hello"],
        replies: {
          right: line("何ですか？", "Nan desu ka?", "Ask for Shibuya."),
          almost: line("すみません、言って。", "Sumimasen, itte.", "“Sumimasen.”"),
          wrong: line("はい？", "Hai?", "Start with “Sumimasen.”"),
        },
      }),
      step({
        id: "ask",
        goal: "Ask the way",
        tryLine: "Shibuya wa doko desu ka?",
        tryNative: "渋谷はどこですか？",
        successOutcome: "served",
        rightAny: ["doko", "どこ", "shibuya", "渋谷"],
        almostAny: ["where", "way"],
        replies: {
          right: line("まっすぐ、それから左。", "Massugu, sorekara hidari.", "Thank him."),
          almost: line("どこ？はっきり。", "Doko? Hakkiri.", "“Doko desu ka?”"),
          wrong: line("何を聞くの？", "Nani wo kiku no?", "Ask where it is."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Arigatou gozaimasu",
        tryNative: "ありがとうございます",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう"],
        almostAny: ["thanks"],
        replies: {
          right: line("いいえ。", "Iie.", "That’s the street."),
          almost: line("ありがとう。", "Arigatou.", "Thank him."),
          wrong: line("一言。", "Hitokoto.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "police_traffic",
    speaker: "KOBAN",
    x: 6.3,
    z: 8.2,
    view: "Mid: a koban officer at a small police box in daylight.",
    opening: { native: "ちょっと止まって。免許証を。", roman: "Chotto tomatte. Menkyoshou wo." },
    heritage: {
      title: "Koban",
      native: "交番",
      body: "You stop. You show. You stay polite.",
    },
    impatient: { native: "早く見せて。", roman: "Hayaku misete." },
    claude: { npc: "You are a Tokyo police officer. Firm, correct. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "stop",
        goal: "Acknowledge",
        tryLine: "Hai",
        tryNative: "はい",
        successOutcome: "welcome",
        rightAny: ["hai", "はい"],
        almostAny: ["yes", "ok"],
        replies: {
          right: line("免許証。", "Menkyoshou.", "Show it."),
          almost: line("はい、言って。", "Hai, itte.", "“Hai.”"),
          wrong: line("聞こえた？止まって。", "Kikoeta? Tomatte.", "Answer him."),
        },
      }),
      step({
        id: "license",
        goal: "Show license",
        tryLine: "Hai, douzo",
        tryNative: "はい、どうぞ",
        successOutcome: "paid",
        rightAny: ["douzo", "どうぞ", "menkyo", "免許"],
        almostAny: ["here", "card"],
        replies: {
          right: line("いいです。行ってください。", "Ii desu. Itte kudasai.", "Thank him."),
          almost: line("見せて — どうぞ。", "Misete — douzo.", "Hand it over."),
          wrong: line("免許証は？", "Menkyoshou wa?", "Show the license."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Arigatou gozaimasu",
        tryNative: "ありがとうございます",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう"],
        almostAny: ["thanks"],
        replies: {
          right: line("気をつけて。", "Ki wo tsukete.", "Go."),
          almost: line("ありがとう。", "Arigatou.", "Thank him."),
          wrong: line("どうぞ。", "Douzo.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "on_a_date",
    speaker: "YUKI",
    x: 1.8,
    z: 6.4,
    view: "Mid: a kissaten table, a woman with iced coffee, sunlit window.",
    opening: { native: "遅れた？", roman: "Okureta?" },
    heritage: {
      title: "Kissaten",
      native: "喫茶店",
      body: "You sit. You ask how they are. Small first.",
    },
    impatient: { native: "何か言ってよ。", roman: "Nanika itte yo." },
    claude: { npc: "You are on a first date in Tokyo. Warm, teasing. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "hi",
        goal: "Greet her",
        tryLine: "Konbanwa, genki?",
        tryNative: "こんばんは、元気？",
        successOutcome: "welcome",
        rightAny: ["konbanwa", "こんばんは", "genki", "元気"],
        almostAny: ["hello", "hi"],
        replies: {
          right: line("元気。何飲む？", "Genki. Nani nomu?", "Order coffee."),
          almost: line("こんばんは、言って。", "Konbanwa, itte.", "Greet her."),
          wrong: line("うん？", "Un?", "Say hello."),
        },
      }),
      step({
        id: "order",
        goal: "Order for the table",
        tryLine: "Kohii futatsu",
        tryNative: "コーヒー二つ",
        successOutcome: "served",
        rightAny: ["kohii", "コーヒー", "futatsu", "二つ"],
        almostAny: ["coffee", "tea"],
        replies: {
          right: line("いいね。話そう。", "Ii ne. Hanasou.", "Thank her."),
          almost: line("コーヒー？二つ。", "Kohii? Futatsu.", "Order two coffees."),
          wrong: line("何か飲む？", "Nanika nomu?", "Order drinks."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank her",
        tryLine: "Arigatou",
        tryNative: "ありがとう",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう"],
        almostAny: ["thanks"],
        replies: {
          right: line("また会おう。", "Mata aou.", "That’s the table."),
          almost: line("ありがとう。", "Arigatou.", "Thank her."),
          wrong: line("もう一言。", "Mou hitokoto.", "Thank her."),
        },
      }),
    ],
  },
  {
    key: "school_teacher",
    speaker: "TANAKA",
    x: 1.2,
    z: 2.2,
    view: "Mid: a school gate, a teacher with a register. Far: bikes, a board.",
    opening: { native: "はい。宿題は出した？", roman: "Hai. Shukudai wa dashita?" },
    heritage: {
      title: "Sensei",
      native: "先生",
      body: "You address the teacher first. Then the ask.",
    },
    impatient: { native: "チャイムが鳴ったよ。", roman: "Chaimu ga natta yo." },
    claude: { npc: "You are a Tokyo teacher. Crisp, kind. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "sensei",
        goal: "Address the teacher",
        tryLine: "Konbanwa sensei",
        tryNative: "こんばんは先生",
        successOutcome: "welcome",
        rightAny: ["sensei", "先生", "konbanwa", "こんばんは"],
        almostAny: ["hello", "teacher"],
        replies: {
          right: line("何？", "Nani?", "Ask about homework."),
          almost: line("先生、言って。", "Sensei, itte.", "“Sensei.”"),
          wrong: line("はい？", "Hai?", "Greet the teacher."),
        },
      }),
      step({
        id: "ask",
        goal: "Ask about homework",
        tryLine: "Shukudai wa itsu desu ka?",
        tryNative: "宿題はいつですか？",
        successOutcome: "served",
        rightAny: ["shukudai", "宿題", "itsu", "いつ"],
        almostAny: ["when", "homework"],
        replies: {
          right: line("明日まで。分かった？", "Ashita made. Wakatta?", "Thank him."),
          almost: line("いつ？聞いて。", "Itsu? Kiite.", "Ask when it is due."),
          wrong: line("何を聞くの？", "Nani wo kiku no?", "Ask about homework."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Arigatou gozaimasu",
        tryNative: "ありがとうございます",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう"],
        almostAny: ["thanks"],
        replies: {
          right: line("行って。授業だ。", "Itte. Jugyou da.", "Go."),
          almost: line("ありがとう。", "Arigatou.", "Thank him."),
          wrong: line("一言。", "Hitokoto.", "Thank him."),
        },
      }),
    ],
  },
  {
    key: "friends_marriage",
    speaker: "OBASAN",
    x: 9.1,
    z: 5.0,
    view: "Mid: a wedding hall lantern, an aunt in a kimono. Far: noren, gold light.",
    opening: { native: "いらっしゃい！食べた？", roman: "Irasshai! Tabeta?" },
    heritage: {
      title: "Kekkonshiki",
      native: "結婚式",
      body: "You bless the couple, then you eat.",
    },
    impatient: { native: "挨拶して、立ってないで。", roman: "Aisatsu shite." },
    claude: { npc: "You are a relative at a Tokyo wedding. Warm. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "bless",
        goal: "Bless the couple",
        tryLine: "Omedetou gozaimasu",
        tryNative: "おめでとうございます",
        successOutcome: "welcome",
        rightAny: ["omedetou", "おめでとう"],
        almostAny: ["congrats", "hello"],
        replies: {
          right: line("座って、食べて。", "Suwatte, tabete.", "Say you ate."),
          almost: line("おめでとう、言って。", "Omedetou, itte.", "Bless them."),
          wrong: line("来たなら言って。", "Kita nara itte.", "Bless them."),
        },
      }),
      step({
        id: "food",
        goal: "Answer about food",
        tryLine: "Hai, tabemashita",
        tryNative: "はい、食べました",
        successOutcome: "served",
        rightAny: ["tabemashita", "食べました", "tabeta", "食べた", "hai", "はい"],
        almostAny: ["ate", "food"],
        replies: {
          right: line("ケーキもどうぞ。", "Keeki mo douzo.", "Thank her."),
          almost: line("食べた？はい、食べました。", "Tabeta? Hai, tabemashita.", "Say you ate."),
          wrong: line("お腹空いた？", "Onaka suita?", "Tell her you ate."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank her",
        tryLine: "Arigatou",
        tryNative: "ありがとう",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう"],
        almostAny: ["thanks"],
        replies: {
          right: line("また来て。", "Mata kite.", "That’s the hall."),
          almost: line("ありがとう。", "Arigatou.", "Thank her."),
          wrong: line("一言。", "Hitokoto.", "Thank her."),
        },
      }),
    ],
  },
  {
    key: "doctor_visit",
    speaker: "DR MORI",
    x: 2.4,
    z: 9.0,
    view: "Mid: a clinic doorway, a doctor in a white coat. Far: a green cross, a queue.",
    opening: { native: "はい、どこが痛い？", roman: "Hai, doko ga itai?" },
    heritage: {
      title: "Itami",
      native: "痛み",
      body: "You name the symptom. The doctor asks the rest.",
    },
    impatient: { native: "次の患者が待ってます。", roman: "Tsugi no kanja ga mattemasu." },
    claude: { npc: "You are a Tokyo clinic doctor. Calm, brief. Speak Japanese.", replyShape: "one short Japanese sentence" },
    steps: [
      step({
        id: "symptom",
        goal: "Name the symptom",
        tryLine: "Atama ga itai desu",
        tryNative: "頭が痛いです",
        successOutcome: "welcome",
        rightAny: ["itai", "痛い", "atama", "頭", "netsu", "熱"],
        almostAny: ["pain", "head", "sick"],
        replies: {
          right: line("いつから？薬を出します。", "Itsu kara? Kusuri wo dashimasu.", "Ask what to take."),
          almost: line("痛い？頭が痛い、言って。", "Itai? Atama ga itai, itte.", "Name the pain."),
          wrong: line("どうした？", "Doushita?", "Say what hurts."),
        },
      }),
      step({
        id: "ask",
        goal: "Ask for medicine",
        tryLine: "Donna kusuri desu ka?",
        tryNative: "どんな薬ですか？",
        successOutcome: "served",
        rightAny: ["kusuri", "薬", "donna", "どんな"],
        almostAny: ["medicine", "tablet"],
        replies: {
          right: line("この薬、食後に。", "Kono kusuri, shokugo ni.", "Thank him."),
          almost: line("薬を聞いて。", "Kusuri wo kiite.", "Ask for the medicine."),
          wrong: line("他に？", "Hoka ni?", "Ask for the medicine."),
        },
      }),
      step({
        id: "thanks",
        goal: "Thank him",
        tryLine: "Arigatou gozaimasu",
        tryNative: "ありがとうございます",
        successOutcome: "complete",
        rightAny: ["arigatou", "ありがとう", "sensei", "先生"],
        almostAny: ["thanks"],
        replies: {
          right: line("お大事に。水を飲んで。", "Odaiji ni.", "That’s the clinic."),
          almost: line("ありがとう。", "Arigatou.", "Thank him."),
          wrong: line("一言。", "Hitokoto.", "Thank him."),
        },
      }),
    ],
  },
];
